services:
  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  express:
    build: ./server
    ports:
      - "4000:4000"
    environment:
      - MQTT_URL=mqtt://mqtt:1883
    depends_on:
      - mqtt

volumes:
  mosquitto_data:
