services:
  mqtt:
    container_name: MQTT
    image: eclipse-mosquitto:latest
    networks:
      - app_network
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./nginx/certs/cf.pem:/mosquitto/certs/cf.pem
      - ./nginx/certs/cf-key.pem:/mosquitto/certs/cf-key.pem

  express:
    container_name: EXPRESS
    build: ./server
    networks:
      - app_network
    depends_on:
      - mqtt

  next:
    container_name: NEXT
    build: ./client
    networks:
      - app_network
    depends_on:
      - express

  nginx:
    container_name: NGINX
    image: nginx:alpine
    networks:
      - app_network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - next
      - express
      - mqtt

networks:
  app_network:
    driver: bridge

volumes:
  mosquitto_data: