services:
  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  express:
    build: ./server
    ports:
      - "4000:4000"
    environment:
      - MQTT_URL=mqtt://mqtt:1883
    depends_on:
      - mqtt

  next:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - express
    environment:
      - NEXT_PUBLIC_HOST=

volumes:
  mosquitto_data:
