services:
  mqtt:
    image: eclipse-mosquitto:latest
    networks:
      - app_network
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./nginx/certs/cf.pem:/mosquitto/certs/cf.pem
      - ./nginx/certs/cf-key.pem:/mosquitto/certs/cf-key.pem

  express:
    build: ./server
    networks:
      - app_network
    environment:
      - MQTT_URL=mqtt://mqtt:1883
    depends_on:
      - mqtt

  next:
    build: ./client
    networks:
      - app_network
    environment:
      - NEXT_PUBLIC_API_HOST=https://api.isaacclloyd.com
      - NEXT_PUBLIC_MQTT_HOST=wss://mqtt.isaacclloyd.com
    depends_on:
      - express

  nginx:
    image: nginx:alpine
    networks:
      - app_network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - next
      - express
      - mqtt

networks:
  app_network:
    driver: bridge

volumes:
  mosquitto_data: