services:
  mqtt:
    container_name: MQTT
    image: eclipse-mosquitto:latest
    networks:
      - app_network
    ports:
      - "1883:1883" # MQTT
      - "9001:9001" # MQTT websocket
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  express:
    container_name: EXPRESS
    build: ./server
    networks:
      - app_network
    ports:
      - "4000:4000" # Express HTTP Server
    depends_on:
      - mqtt

  next:
    container_name: NEXT
    build: ./client
    networks:
      - app_network
    ports:
      - "3000:3000" # Next.js
    depends_on:
      - express

networks:
  app_network:
    driver: bridge

volumes:
  mosquitto_data:
